"use client";

// Opens the generated project in a live StackBlitz IDE by POSTing the files to
// https://stackblitz.com/run (their documented form API). No backend needed.

import { toast } from "@/lib/toast";
import type { GenFile } from "@/lib/steps";

export default function OpenInStackBlitz({
  files,
  title,
  className = "btn btn-ghost",
}: {
  files: GenFile[];
  title?: string;
  className?: string;
}) {
  const open = () => {
    if (!files.length) {
      toast.error("No files to open yet");
      return;
    }
    const hasPkg = files.some((f) => /(^|\/)package\.json$/i.test(f.path));
    const hasHtml = files.some((f) => /\.html$/i.test(f.path));
    const template = hasPkg ? "node" : hasHtml ? "html" : "javascript";

    const form = document.createElement("form");
    form.method = "POST";
    form.action = "https://stackblitz.com/run";
    form.target = "_blank";
    form.style.display = "none";

    const field = (name: string, value: string) => {
      const ta = document.createElement("textarea"); // textarea holds multiline file contents
      ta.name = name;
      ta.value = value;
      form.appendChild(ta);
    };

    field("project[title]", title || "Vibex project");
    field("project[description]", "Generated by Vibex — from idea to code, automatically.");
    field("project[template]", template);
    for (const f of files) field(`project[files][${f.path}]`, f.content);

    document.body.appendChild(form);
    form.submit();
    window.setTimeout(() => form.remove(), 1000);
    toast.success("Opening in StackBlitz…");
  };

  return (
    <button type="button" className={className} onClick={open}>
      ↗ Open in StackBlitz
    </button>
  );
}
