"use client";

// A real, full IDE embedded from StackBlitz (WebContainers): editor + file tree + a real in-browser
// terminal (npm / node / bash) + live preview — the same class of environment as Firebase Studio,
// but $0 and no backend for us. The inline embed is the primary experience; "Open in new tab" is a
// guaranteed-working fallback (a top-level navigation, not an iframe handshake), and "Save to Vibex"
// reads the VM's files back so edits still persist to the project.

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import sdk, { type VM, type Project } from "@stackblitz/sdk";
import type { GenFile } from "@/lib/steps";
import { saveProjectFiles } from "@/app/actions";
import { toast } from "@/lib/toast";
import styles from "./StackBlitzIDE.module.css";

// Never persist the WebContainer's install/build junk back to the project.
const SKIP = /(^|\/)(node_modules|\.git|\.cache|dist|\.stackblitz)\/|(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml)$/;

function toFiles(files: GenFile[]): Record<string, string> {
  const map: Record<string, string> = {};
  for (const f of files) map[f.path] = f.content;
  // Static apps get a tiny Vite dev server so the WebContainer boots with a terminal + live preview.
  if (!map["package.json"]) {
    map["package.json"] =
      JSON.stringify({ name: "vibex-app", private: true, scripts: { start: "vite", dev: "vite" }, devDependencies: { vite: "^5.4.0" } }, null, 2) + "\n";
  }
  return map;
}

export default function StackBlitzIDE({ files: initial, projectId, title }: { files: GenFile[]; projectId?: string; title?: string }) {
  const hostRef = useRef<HTMLDivElement>(null);
  const vmRef = useRef<VM | null>(null);
  const embeddedRef = useRef(false);
  const [ready, setReady] = useState(false);
  const [slow, setSlow] = useState(false);
  const [saving, setSaving] = useState(false);

  const project = useMemo<Project>(
    () => ({ title: title || "Vibex project", description: "Generated by Vibex", template: "node", files: toFiles(initial) }),
    [initial, title],
  );
  const openFile = useMemo(
    () => initial.find((f) => /index\.html$/i.test(f.path))?.path ?? initial[0]?.path ?? "index.html",
    [initial],
  );
  const projectRef = useRef(project);
  projectRef.current = project;
  const openNewTab = useCallback(() => sdk.openProject(projectRef.current, { openFile, newWindow: true }), [openFile]);

  useEffect(() => {
    // Run ONCE — React StrictMode double-invokes effects in dev, and a cleanup that wiped the host
    // would tear down the iframe mid-embed and break embedProject's form-POST navigation.
    if (embeddedRef.current) return;
    const host = hostRef.current;
    if (!host) return;
    embeddedRef.current = true;
    // embedProject REPLACES the target node with its iframe; React only manages `host` (and removes
    // it, iframe included, on real unmount), so no manual cleanup is needed.
    const target = document.createElement("div");
    target.style.height = "100%";
    host.appendChild(target);
    sdk
      .embedProject(target, projectRef.current, { height: "100%", view: "default", openFile, terminalHeight: 34, theme: "dark", showSidebar: true })
      .then((vm) => { vmRef.current = vm; setReady(true); })
      .catch(() => { /* embed didn't connect — the fallback overlay offers "Open in new tab" */ });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Separate effect (survives StrictMode's double-invoke): if the embed hasn't connected in a few
  // seconds, reveal the "Open in new tab" fallback.
  useEffect(() => {
    const t = window.setTimeout(() => setSlow(true), 9000);
    return () => window.clearTimeout(t);
  }, []);

  const save = useCallback(async () => {
    const vm = vmRef.current;
    if (!vm || !projectId || saving) return;
    setSaving(true);
    try {
      const snap = await vm.getFsSnapshot();
      if (!snap) throw new Error("no snapshot");
      const out: GenFile[] = Object.entries(snap)
        .filter(([p]) => !SKIP.test(p))
        .map(([path, content]) => ({ path, content: String(content) }));
      const res = await saveProjectFiles(projectId, out);
      if (res?.ok) toast.success("Saved to Vibex"); else toast.error("Couldn’t save");
    } catch { toast.error("Couldn’t read the IDE files"); }
    setSaving(false);
  }, [projectId, saving]);

  return (
    <div className={styles.wrap}>
      <div className={styles.bar}>
        <span className={styles.brand}>StackBlitz IDE — real terminal, npm &amp; live preview</span>
        <span className={styles.barRight}>
          <button type="button" className={styles.ghost} onClick={openNewTab}>Open in new tab ↗</button>
          {projectId && (
            <button type="button" className={styles.save} onClick={() => void save()} disabled={!ready || saving} title={ready ? "Read the IDE's files back into your project" : "Opens once the IDE is ready"}>
              {saving ? "Saving…" : "Save to Vibex"}
            </button>
          )}
        </span>
      </div>
      <div className={styles.hostWrap}>
        <div ref={hostRef} className={styles.host} />
        {!ready && !slow && (
          <div className={styles.booting} aria-live="polite">
            <span className={styles.spinner} aria-hidden />
            <p className={styles.fbText}>Booting the IDE… the first launch spins up a container, so it takes ~10–20s.</p>
          </div>
        )}
        {slow && !ready && (
          <div className={styles.fallback}>
            <p className={styles.fbText}>The embedded IDE is taking a moment (some browsers block embedded editors).</p>
            <button type="button" className={styles.save} onClick={openNewTab}>Open the full IDE in a new tab ↗</button>
          </div>
        )}
      </div>
    </div>
  );
}
